[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","node"]}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
